version: "3.9"

services:
    php-fpm:
        volumes:
            - ./application:/var/www/application
            - var:/var/www/application/var
        environment:
            PHP_IDE_CONFIG: "serverName=application"

    nginx:
        volumes:
            - ./application/public:/var/www/application/public:ro
            - ./docker/etc/nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - "8001:80"

    postgres:
        ports:
            - "5432:5432"

volumes:
    var: ~
