version: "3.9"

services:
    php-fpm:
        build:
            context: .
            dockerfile: ./docker/build/php-fpm/Dockerfile

    nginx:
        build:
            context: .
            dockerfile: ./docker/build/nginx/Dockerfile
        depends_on:
            - php-fpm
